apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.name | default .Release.Name }}
  namespace: {{ .Values.global.targetNamespace | default "argocd" }}
  annotations:
    argocd.argoproj.io/sync-wave: '{{ .Values.global.syncWave | default "-4" }}'
  labels:
    app.kubernetes.io/name: metallb
    managed-by: argocd
    component: infrastructure
    helm.sh/chart: {{ include "metallb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  project: {{ .Values.global.project | default "platform" }}
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: {{ .Values.chart.version | default "0.14.8" }}
      helm:
        releaseName: metallb
        values: |
          controller:
            enabled: true
          speaker:
            enabled: true
            frr:
              enabled: false
  destination:
    server: {{ .Values.global.server | default "https://kubernetes.default.svc" }}
    namespace: {{ .Values.namespace | default "metallb-system" }}
  syncPolicy:
    automated:
      prune: {{ .Values.syncPolicy.automated.prune | default true }}
      selfHeal: {{ .Values.syncPolicy.automated.selfHeal | default true }}
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - PrunePropagationPolicy=foreground
      - Replace=true
    retry:
      limit: {{ .Values.syncPolicy.retry.limit | default 5 }}
      backoff:
        duration: {{ .Values.syncPolicy.retry.backoff.duration | default "5s" }}
        factor: {{ .Values.syncPolicy.retry.backoff.factor | default 2 }}
        maxDuration: {{ .Values.syncPolicy.retry.backoff.maxDuration | default "3m" }}