---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "prometheus.fullname" . }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '4'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: prometheus
    managed-by: argocd
    component: monitoring
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  project: platform
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 67.2.0
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/platform/charts/prometheus/values.yaml
    - repoURL: {{ .Values.global.repoURL | default "https://github.com/your-org/pn-infra.git" }}
      targetRevision: {{ .Values.global.targetRevision | default "v1.2.0-p0-infra" }}
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - PrunePropagationPolicy=foreground
      - Replace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle