apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-infrastructure
  namespace: argocd
  labels:
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/part-of: storage-infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: 20
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:pnow-devsupreme/pn-infra.git
    targetRevision: v0.2.0-p0-infra
    path: applications/infrastructure/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-storage
  info:
    - name: Description
      value: "This application is responsible to deploy and maintain the storage infrastructure of pnats platform"
    - name: Documentation
      value: https://developers.pnats.tech
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 10
