apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-infrastructure
  namespace: argocd
  labels:
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/part-of: storage-infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/sync-options: "SkipDryRun=true,SkipDryRunOnMissingResource=true,ServerSideApply=true"
    argocd.argoproj.io/compare-options: "IgnoreExtraneous"
    argocd.argoproj.io/tracking-method: "annotation"
spec:
  project: default
  source:
    repoURL: git@github.com:pnow-devsupreme/pn-infra.git
    targetRevision: v0.2.0-p0-infra
    path: applications/infrastructure/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: storage-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: "30s"
        factor: 2
        maxDuration: "5m"
