---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "grafana.fullname" . }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
{{ include "grafana.labels" . | nindent 4 }}
spec:
  project: platform
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 8.11.6
      helm:
        releaseName: grafana
        valueFiles:
          - $values/platform/charts/grafana/values.yaml
    - repoURL: {{ .Values.global.repoURL | default "git@github.com:pnow-devsupreme/pn-infra.git" }}
      targetRevision: {{ .Values.global.targetRevision | default "main" }}
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - PrunePropagationPolicy=foreground
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
