apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.rook.io/release"
    targetRevision: v1.15.7
    chart: rook-ceph
    helm:
      valuesObject:
        # CRD Configuration
        crds:
          enabled: true

        # Image Configuration
        image:
          repository: docker.io/rook/ceph
          pullPolicy: IfNotPresent
          tag: v1.15.7

        # Resource Configuration
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 500Mi

        # Security Configuration
        pspEnable: false
        rbacEnable: true
        securityContext:
          runAsUser: 2016
          runAsGroup: 2016
          fsGroup: 2016
        containerSecurityContext:
          runAsNonRoot: true
          runAsUser: 2016
          runAsGroup: 2016
          capabilities:
            drop: ["ALL"]

        # Node Placement Configuration
        nodeSelector:
          kubernetes.io/hostname: pn-hyd-wr02-1a,pn-hyd-ms01-1a,pn-hyd-ms02-1a
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        placement:
          all:
            nodeSelector:
              kubernetes.io/hostname: pn-hyd-wr02-1a,pn-hyd-ms01-1a,pn-hyd-ms02-1a
            tolerations:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
                effect: NoSchedule

        # CSI Configuration
        csi:
          enableCSIHostNetwork: true
          provisionerReplicas: 4
          enableCSIEncryption: false
          logLevel: 0
          enableVolumeReplication: true

          # CSI Resources
          csiRBDProvisionerResource:
            limits:
              cpu: 2
              memory: 1Gi
            requests:
              cpu: 1
              memory: 500Mi
          csiRBDPluginResource:
            limits:
              cpu: 2
              memory: 1Gi
            requests:
              cpu: 1
              memory: 500Mi

          # CSI Topology
          topology:
            enabled: true
            domainLabels:
              - kubernetes.io/hostname
              - topology.kubernetes.io/zone

          # CSI Node Placement
          # CSI provisioner configuration - handles the actual mounting of volumes on nodes
          provisionerNodeAffinity: "kubernetes.io/hostname=pn-hyd-wr02-1a,pn-hyd-ms01-1a,pn-hyd-ms02-1a"
          provisionerTolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
          provisionerPriorityClassName: system-cluster-critical

          # CSI plugin placement - also targets the control plane node
          pluginNodeAffinity: "kubernetes.io/hostname=pn-hyd-wr02-1a,pn-hyd-ms01-1a,pn-hyd-ms02-1a"
          pluginTolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
          pluginPriorityClassName: system-node-critical

        # Discovery Configuration
        enableDiscoveryDaemon: true
        discoveryDaemonInterval: 60m
        discover:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - pn-hyd-wr02-1a
                        - pn-hyd-ms01-1a
                        - pn-hyd-ms02-1a
          tolerationKey: node-role.kubernetes.io/control-plane
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule

        # Logging Configuration
        logLevel: INFO

        # Priority Configuration
        priorityClassName: system-cluster-critical
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
