---
# Global configuration
global:
  repoURL: "https://github.com/your-org/pn-infra.git"
  targetRevision: "v1.2.0-p0-infra"
  server: "https://kubernetes.default.svc"
  targetNamespace: "argocd"
  project: "platform"
  syncWave: "-4"

# MetalLB configuration
chart:
  version: "0.14.8"  # Helm chart version

namespace: "metallb-system"

# Sync policy configuration
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  retry:
    limit: 5
    backoff:
      duration: "5s"
      factor: 2
      maxDuration: "3m"