---
# Global configuration
global:
  repoURL: 'https://github.com/pnow-devsupreme/pn-infra.git'
  targetRevision: 'main'
  server: 'https://kubernetes.default.svc'
  targetNamespace: 'argocd'
  project: 'platform'
  syncWave: '-4'

# Labels configuration
labels:
  component: infrastructure
  managed-by: argocd  # Override default Helm with ArgoCD

# MetalLB configuration
chart:
  version: '0.14.8' # Helm chart version

namespace: 'metallb-system'

# Sync policy configuration
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  retry:
    limit: 5
    backoff:
      duration: '5s'
      factor: 2
      maxDuration: '3m'

# MetalLB Configuration (merged from metallb-config)
metallb:
  namespace: "metallb-system"
  
  ipAddressPool:
    enabled: true
    name: "public-traffic-pool"
    addresses:
      - "192.168.101.121-192.168.101.125"
    autoAssign: true
    avoidBuggyIPs: true
    
  l2Advertisement:
    enabled: true
    name: "public-traffic-advertisement"
    ipAddressPools:
      - "public-traffic-pool"
    nodeSelectors:
      # Target worker nodes with VLAN 101 interfaces
      - matchLabels:
          kubernetes.io/hostname: "k8s-worker-01"
      - matchLabels:
          kubernetes.io/hostname: "k8s-worker-02"
      - matchLabels:
          kubernetes.io/hostname: "k8s-worker-03"
      - matchLabels:
          kubernetes.io/hostname: "k8s-worker-04"
      - matchLabels:
          kubernetes.io/hostname: "k8s-worker-05"
