---
# Ingress-NGINX Helm Chart Values
# https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx

controller:
  # Replica configuration
  replicaCount: 2

  # Resource configuration
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  # Service configuration
  service:
    type: LoadBalancer
    # loadBalancerIP: ""  # MetalLB will auto-assign
    externalTrafficPolicy: Local

  # Autoscaling
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  # Metrics
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false

  # Pod disruption budget
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

  # Allow snippets for advanced configurations (e.g., ArgoCD GRPC)
  allowSnippetAnnotations: true

  # Additional configuration
  config:
    # Enable snippets in ConfigMap as well
    allow-snippet-annotations: "true"

# Default backend
defaultBackend:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 50m
      memory: 64Mi
