# Default values for metallb-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# MetalLB Configuration
metallb:
  namespace: "metallb-system"
  
  ipAddressPool:
    enabled: true
    name: "public-traffic-pool"
    addresses:
      - "192.168.101.121-192.168.101.125"
    autoAssign: true
    avoidBuggyIPs: true
    
  l2Advertisement:
    enabled: true
    name: "public-traffic-advertisement"
    ipAddressPools:
      - "public-traffic-pool"
    nodeSelectors:
      # Target worker nodes with VLAN 101 interfaces
      - matchLabels:
          kubernetes.io/hostname: "k8s-worker-01"
      - matchLabels:
          kubernetes.io/hostname: "k8s-worker-02"
      - matchLabels:
          kubernetes.io/hostname: "k8s-worker-03"
      - matchLabels:
          kubernetes.io/hostname: "k8s-worker-04"
      - matchLabels:
          kubernetes.io/hostname: "k8s-worker-05"