apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: snoorullah@proficientnowtech.com
    privateKeySecretRef:
      # This is the secret Cert-manager will create to store its account key
      name: letsencrypt-dns-account-key
    solvers:
      - dns01:
          cloudflare:
            # You must match the name/namespace of the secret you created
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
