---
# Cert-Manager Helm Chart Values
# https://github.com/cert-manager/cert-manager/tree/master/deploy/charts/cert-manager

# Install CRDs
installCRDs: true

# Namespace (informational - set by ArgoCD)
global:
  leaderElection:
    namespace: cert-manager

# Resource configuration
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi

# Webhook configuration
webhook:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

# CA Injector configuration
cainjector:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Prometheus monitoring
prometheus:
  enabled: true
  servicemonitor:
    enabled: false
