---
# Global configuration
global:
  repoURL: 'git@github.com:pnow-devsupreme/pn-infra.git'
  targetRevision: 'main'
  server: 'https://kubernetes.default.svc'
  targetNamespace: 'argocd'
  project: 'platform'
  syncWave: '-2'

# Labels configuration
labels:
  component: infrastructure
  managed-by: argocd  # Override default Helm with ArgoCD

# Cert-Manager configuration
chart:
  version: 'v1.16.1' # Helm chart version

namespace: 'cert-manager'

# Sync policy configuration
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  retry:
    limit: 5
    backoff:
      duration: '5s'
      factor: 2
      maxDuration: '3m'
