{{- if .Values.nginxConfig.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginxConfig.name }}
  namespace: {{ .Values.ingressNginx.namespace }}
  labels:
    {{- range $key, $value := .Values.commonLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{- range $key, $value := .Values.commonSelectors }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{- range $key, $value := .Values.nginxConfig.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  # Security headers
  proxy-set-headers: {{ .Values.nginxConfig.proxy.setHeaders }}
  ssl-protocols: {{ .Values.nginxConfig.ssl.protocols }}
  ssl-ciphers: {{ .Values.nginxConfig.ssl.ciphers }}

  # Performance tuning
  proxy-body-size: {{ .Values.nginxConfig.proxy.bodySize }}
  proxy-read-timeout: {{ .Values.nginxConfig.proxy.readTimeout | quote }}
  proxy-send-timeout: {{ .Values.nginxConfig.proxy.sendTimeout | quote }}
  proxy-connect-timeout: {{ .Values.nginxConfig.proxy.connectTimeout | quote }}

  # GZIP compression
  enable-gzip: {{ .Values.nginxConfig.gzip.enabled | quote }}
  gzip-types: {{ .Values.nginxConfig.gzip.types }}

  # Rate limiting
  limit-connections: {{ .Values.nginxConfig.rateLimit.connections | quote }}
  limit-rate-after: {{ .Values.nginxConfig.rateLimit.rateAfter }}
  limit-rate: {{ .Values.nginxConfig.rateLimit.rate }}
{{- end }}
