---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "rook-ceph.fullname" . }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  labels:
    app.kubernetes.io/name: rook-ceph
    managed-by: argocd
    component: storage
    {{- include "rook-ceph.labels" . | nindent 4 }}
spec:
  project: platform
  sources:
    - repoURL: https://charts.rook.io/release
      chart: rook-ceph
      targetRevision: v1.18.3
      helm:
        releaseName: rook-ceph
        valueFiles:
          - $values/platform/charts/rook-ceph/values.yaml
    - repoURL: {{ .Values.global.repoURL | default "https://github.com/your-org/pn-infra.git" }}
      targetRevision: {{ .Values.global.targetRevision | default "v1.2.0-p0-infra" }}
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - PrunePropagationPolicy=foreground
      - Replace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # Health check configuration
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
        - /status