---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.name | default .Release.Name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: argocd-self
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: platform
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: {{ .Values.argocd.version | default "7.7.8" }}
      helm:
        releaseName: argocd
        valueFiles:
          - $values/v0.2.0/platform/charts/argocd-self/values.yaml
    - repoURL: {{ .Values.global.repoURL | default "git@github.com:pnow-devsupreme/pn-infra.git" }}
      targetRevision: {{ .Values.global.targetRevision | default "main" }}
      ref: values
    - repoURL: {{ .Values.global.repoURL | default "git@github.com:pnow-devsupreme/pn-infra.git" }}
      targetRevision: {{ .Values.global.targetRevision | default "main" }}
      path: v0.2.0/platform/charts/argocd-self/config
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - PrunePropagationPolicy=foreground
      - Replace=false
      - SkipDryRunOnMissingResource=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jqPathExpressions:
        - .status
        - .operation
    - group: ''
      kind: Secret
      name: argocd-initial-admin-secret
      jsonPointers:
        - /data
    - group: ''
      kind: Secret
      name: argocd-secret
      jsonPointers:
        - /data/admin.password
        - /data/admin.passwordMtime