---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    platform.pnats.cloud/org: ProficientNowTech
    platform.pnats.cloud/maintained-by: platform-team
    platform.pnats.cloud/environment: production
  annotations:
    platform.pnats.cloud/description: "Platform utilities and operators namespace"
