{{- if .Values.clusterIssuerStaging.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuerStaging.name }}
  annotations:
    {{- range $key, $value := .Values.commonAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    {{- range $key, $value := .Values.commonLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- range $key, $value := .Values.commonSelectors }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- range $key, $value := .Values.clusterIssuerStaging.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  acme:
    server: {{ .Values.clusterIssuerStaging.acme.server }}
    email: {{ .Values.clusterIssuerStaging.acme.email }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuerStaging.acme.privateKeySecretName }}
    solvers:
      - dns01:
          cloudflare:
            email: {{ .Values.clusterIssuerStaging.solver.dns01.cloudflare.email }}
            apiTokenSecretRef:
              name: {{ .Values.clusterIssuerStaging.solver.dns01.cloudflare.apiTokenSecretName }}
              key: {{ .Values.clusterIssuerStaging.solver.dns01.cloudflare.apiTokenSecretKey }}
        selector:
          dnsZones:
            {{- toYaml .Values.clusterIssuerStaging.solver.dns01.dnsZones | nindent 12 }}
{{- end }}
