---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aiml-workloads
  namespace: machine-learning
  labels:
    - apps.kubernetes.io/name: aiml-workloads
    - apps.kubernetes.io/part-of: ml-infra-layer
    - managed-by: ml-infra
spec:
  description: "Project to deploy AI/ML workloads be it inference, training or data preparation/manipulation"
  sourceRepos:
    - "*"
  destinations:
    - namespace: "prod-aiml-workloads*"
      server: https://kubernetes.default.svc
      name: in-cluster
    - namespace: "staging-aiml-workloads*"
      server: https://kubernetes.default.svc
      name: in-cluster
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: Application
