apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infrastructure.yaml
  # Uncomment as you implement more applications
  # - applications.yaml
  # - workloads.yaml
  # - environments.yaml
