{{- if .Values.letsencrypt.production.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app.kubernetes.io/name: cert-manager-issuers
    managed-by: argocd
    helm.sh/chart: {{ include "cert-manager-config.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.letsencrypt.production.email }}
    privateKeySecretRef:
      name: letsencrypt-dns-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: {{ .Values.letsencrypt.production.cloudflare.secretName }}
              key: {{ .Values.letsencrypt.production.cloudflare.secretKey }}
{{- end }}

{{- if .Values.letsencrypt.staging.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app.kubernetes.io/name: cert-manager-issuers
    managed-by: argocd
    helm.sh/chart: {{ include "cert-manager-config.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.letsencrypt.staging.email }}
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: {{ .Values.letsencrypt.staging.cloudflare.secretName }}
              key: {{ .Values.letsencrypt.staging.cloudflare.secretKey }}
{{- end }}