---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Chart.Name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "{{ index .Chart.Annotations "platform.pn-infra.io/sync-wave" }}"
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: {{ .Values.labels.component }}
    app.kubernetes.io/managed-by: {{ .Values.labels.managedBy | default "argocd" }}
spec:
  project: default
  sources:
    - repoURL: https://charts.rook.io/release
      chart: rook-ceph-cluster
      targetRevision: {{ .Chart.AppVersion }}
      helm:
        releaseName: rook-ceph-cluster
        parameters:
          - name: operatorNamespace
            value: {{ .Values.operatorNamespace }}
        valueFiles:
          - $values/v0.2.0/platform/charts/rook-ceph-cluster/values.yaml
    - repoURL: {{ .Values.global.repoURL | default "https://github.com/pnow-devsupreme/pn-infra.git" }}
      targetRevision: {{ .Values.global.targetRevision | default "main" }}
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: ceph.rook.io
    kind: CephCluster
    jqPathExpressions:
    - .status
    - .spec.cephVersion.image
    - .spec.placement
  - group: ceph.rook.io
    kind: CephBlockPool
    jqPathExpressions:
    - .status
  - group: ceph.rook.io
    kind: CephFilesystem
    jqPathExpressions:
    - .status
  - group: ceph.rook.io
    kind: CephObjectStore
    jqPathExpressions:
    - .status