---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.name | default .Release.Name }}
  namespace: {{ .Values.global.targetNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.global.syncWave | quote }}
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: platform
spec:
  project: {{ .Values.global.project }}
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns/
      chart: external-dns
      targetRevision: {{ .Values.chart.version }}
      helm:
        releaseName: external-dns
        values: |
          image:
            repository: registry.k8s.io/external-dns/external-dns
            tag: {{ .Values.image.tag }}

          provider: cloudflare

          domainFilters:
            - {{ .Values.cloudflare.domain }}

          policy: {{ .Values.policy }}

          registry: txt
          txtOwnerId: {{ .Values.txtOwnerId }}

          interval: {{ .Values.interval }}

          logLevel: {{ .Values.logLevel }}
          logFormat: {{ .Values.logFormat }}

          sources:
            - ingress
            - service

          env:
            - name: CF_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cloudflare.secretName }}
                  key: {{ .Values.cloudflare.secretKey }}

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          serviceAccount:
            create: true

          rbac:
            create: true

          replicas: {{ .Values.replicas }}

          metrics:
            enabled: {{ .Values.metrics.enabled }}
            port: 7979
    - repoURL: {{ .Values.global.repoURL }}
      targetRevision: {{ .Values.global.targetRevision }}
      path: v0.2.0/platform/apps/external-dns-config
      helm:
        releaseName: external-dns-config
  destination:
    server: {{ .Values.global.server }}
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: {{ .Values.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.syncPolicy.automated.selfHeal }}
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: {{ .Values.syncPolicy.retry.limit }}
      backoff:
        duration: {{ .Values.syncPolicy.retry.backoff.duration }}
        factor: {{ .Values.syncPolicy.retry.backoff.factor }}
        maxDuration: {{ .Values.syncPolicy.retry.backoff.maxDuration }}
