---
apiVersion: v1
kind: Service
metadata:
  name: platform-kv
  namespace: platform-kv-redis-cluster
  labels:
    app.kubernetes.io/name: platform-kv
    app.kubernetes.io/component: redis-replication
    redis_setup_type: replication
    role: replication
  annotations:
    # Prometheus metrics scraping
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
    # External DNS configuration
    external-dns.alpha.kubernetes.io/hostname: platform-kv.pnats.cloud
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  type: LoadBalancer
  ports:
  - name: redis-client
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app.kubernetes.io/name: platform-kv
    redis_setup_type: replication
    role: replication
