{{- if .Values.ipAddressPool.addresses }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipAddressPool.name }}
  namespace: {{ .Values.namespace }}
spec:
  addresses:
    {{- toYaml .Values.ipAddressPool.addresses | nindent 4 }}
  autoAssign: {{ .Values.ipAddressPool.autoAssign }}
{{- end }}