apiVersion: v2
name: external-dns
description: External-DNS for automatic DNS record management with Cloudflare
type: application
version: 0.1.0
appVersion: "v0.15.0"

keywords:
  - dns
  - cloudflare
  - external-dns
  - automation

maintainers:
  - name: Platform Team
    email: snoorullah@proficientnowtech.com

annotations:
  category: Infrastructure
  component: dns-management