---
# External-DNS Helm Chart Values
# https://github.com/kubernetes-sigs/external-dns/tree/master/charts/external-dns

# Provider configuration
provider: cloudflare

# Sources to monitor
sources:
  - ingress
  - service

# Domain filter
domainFilters:
  - pnats.cloud

# Policy
policy: sync

# TXT owner ID
txtOwnerId: external-dns-pnats

# Cloudflare configuration
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token

# Deployment configuration
replicas: 1

# Resource configuration
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Operational configuration
interval: 1m
logLevel: info
logFormat: text

# Metrics
serviceMonitor:
  enabled: false
