{{- range .Values.projects }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  description: {{ .description | quote }}
  sourceRepos:
    {{- range .sourceRepos }}
    - {{ . | quote }}
    {{- end }}
  destinations:
    {{- range .destinations }}
    - namespace: {{ .namespace }}
      server: {{ .server | default "https://kubernetes.default.svc" }}
      name: {{ .name | default "in-cluster" }}
    {{- end }}
  clusterResourceWhitelist:
    {{- range .clusterResources }}
    - group: {{ .group | quote }}
      kind: {{ .kind | quote }}
    {{- end }}
  namespaceResourceWhitelist:
    {{- range .namespaceResources }}
    - group: {{ .group | quote }}
      kind: {{ .kind | quote }}
    {{- end }}
  roles:
    - name: admin
      description: Admin access to {{ .name }} project
      policies:
        - p, proj:{{ .name }}:admin, applications, *, {{ .name }}/*, allow
        - p, proj:{{ .name }}:admin, repositories, *, *, allow
      groups:
        - platform-admins
{{- end }}
