apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: argocd
spec:
  description: ML/Compute Workload Deployments
  sourceRepos:
    - git@github.com:pnow-devsupreme/pn-infra.git
  destinations:
    - namespace: "workloads*"
      server: https://kubernetes.default.svc
    - namespace: "argocd"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceNamespaces:
    - "workloads*"
    - "argocd"
