---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  name: platform-kv
  namespace: platform-kv-redis-cluster
  labels:
    app.kubernetes.io/name: platform-kv
    app.kubernetes.io/component: redis-replication
    app.kubernetes.io/part-of: platform-infrastructure
    criticality: high
  annotations:
    description: "Redis replication cluster for platform services (Infisical, etc.)"
spec:
  # High Availability Configuration
  # 1 master + 2 replicas for robust failover
  clusterSize: 3

  # Kubernetes Configuration
  kubernetesConfig:
    image: quay.io/opstree/redis
    imagePullPolicy: IfNotPresent

    # Resource allocation for platform workloads
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi

  # Note: External LoadBalancer service defined separately in platform-kv-repl-svc.yaml
  # Redis Configuration
  redisConfig:
    additionalRedisConfig: redis-external-config

  # Persistent Storage - Ceph Block (RBD)
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: ceph-block
        resources:
          requests:
            storage: 10Gi

  # Pod Anti-Affinity for HA
  # Ensure Redis pods are spread across different nodes
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - platform-kv
          topologyKey: kubernetes.io/hostname

  # Redis Exporter for Monitoring
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

  # Health Checks
  readinessProbe:
    failureThreshold: 5
    initialDelaySeconds: 15
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
  livenessProbe:
    failureThreshold: 5
    initialDelaySeconds: 15
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5

  # Pod Disruption Budget
  pdb:
    enabled: true
    maxUnavailable: 1

  # Security Context
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false # Redis needs write for RDB/AOF
    runAsNonRoot: true

  # Tolerations for control-plane scheduling
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
