apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls-secret
  namespace: argocd
spec:
  secretName: argocd-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - argocd.pnats.cloud
