---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.name | default .Release.Name }}
  namespace: {{ .Values.global.targetNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.global.syncWave }}
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: platform
spec:
  project: {{ .Values.global.project }}
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: {{ .Values.chart.version }}
      helm:
        releaseName: ingress-nginx
        values: |
          controller:
            service:
              type: LoadBalancer
              loadBalancerIP: {{ .Values.loadBalancerIP }}
            config:
              use-real-ip: "true"
              compute-full-forwarded-for: "true"
              use-forwarded-headers: "true"
            metrics:
              enabled: true
            admissionWebhooks:
              enabled: true
    - repoURL: {{ .Values.global.repoURL }}
      targetRevision: {{ .Values.global.targetRevision }}
      path: v0.2.0/platform/apps/ingress-nginx-config
      helm:
        releaseName: ingress-nginx-config
  destination:
    server: {{ .Values.global.server }}
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: {{ .Values.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.syncPolicy.automated.selfHeal }}
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - PrunePropagationPolicy=foreground
      - Replace=true
    retry:
      limit: {{ .Values.syncPolicy.retry.limit }}
      backoff:
        duration: {{ .Values.syncPolicy.retry.backoff.duration }}
        factor: {{ .Values.syncPolicy.retry.backoff.factor }}
        maxDuration: {{ .Values.syncPolicy.retry.backoff.maxDuration }}
