---
apiVersion: v1
kind: Service
metadata:
  name: temporal-postgres-exporter
  namespace: temporal
  labels:
    app.kubernetes.io/name: temporal-db
    app.kubernetes.io/component: postgres-exporter
spec:
  type: ClusterIP
  ports:
  - name: exporter
    port: 9187
    targetPort: 9187
    protocol: TCP
  selector:
    application: spilo
    cluster-name: temporal-postgres
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: temporal-postgres-exporter
  namespace: temporal
  labels:
    app.kubernetes.io/name: temporal-db
    app.kubernetes.io/component: postgres-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "temporal-db"
      app.kubernetes.io/component: "postgres-exporter"
  endpoints:
  - port: exporter
    interval: 30s
    path: /metrics
