apiVersion: v2
name: target-chart
description: A Helm chart that generates ArgoCD applications for platform services (Application Factory pattern)
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - argocd
  - applications
  - platform
  - kubernetes
  - template-driven
  - application-factory

annotations:
  category: Platform
  platform.pn-infra.io/component: target-chart
  platform.pn-infra.io/framework: openspec
  platform.pn-infra.io/pattern: template-driven