{{- if .Values.metallb.ipAddressPool.enabled }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.metallb.ipAddressPool.name }}
  namespace: {{ .Values.metallb.namespace }}
  labels:
    app.kubernetes.io/name: metallb-config
    managed-by: argocd
    helm.sh/chart: {{ include "metallb-config.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  addresses:
  {{- range .Values.metallb.ipAddressPool.addresses }}
  - {{ . }}
  {{- end }}
  autoAssign: {{ .Values.metallb.ipAddressPool.autoAssign }}
  avoidBuggyIPs: {{ .Values.metallb.ipAddressPool.avoidBuggyIPs }}
{{- end }}

{{- if .Values.metallb.l2Advertisement.enabled }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.metallb.l2Advertisement.name }}
  namespace: {{ .Values.metallb.namespace }}
  labels:
    app.kubernetes.io/name: metallb-config
    managed-by: argocd
    helm.sh/chart: {{ include "metallb-config.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ipAddressPools:
  {{- range .Values.metallb.l2Advertisement.ipAddressPools }}
  - {{ . }}
  {{- end }}
  {{- if .Values.metallb.l2Advertisement.nodeSelectors }}
  nodeSelectors:
  {{- range .Values.metallb.l2Advertisement.nodeSelectors }}
  - matchLabels:
    {{- range $key, $value := .matchLabels }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}