apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray-operator-crds
  namespace: argocd
  labels:
    app.kubernetes.io/name: kuberay-operator
    app.kubernetes.io/part-of: gpu-infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/ray-project/kuberay
    targetRevision: v1.0.0-rc.0
    path: helm-chart/kuberay-operator/crds
  destination:
    namespace: gpu-resources
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - Replace=true
