apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray-operator-crds
  namespace: argocd
  labels:
    apps.kubernetes.io/name: kuberay-operator-crds
    apps.kubernetes.io/part-of: gpu-infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: 10
    argocd.argoproj.io/sync-options: "SkipDryRun=true,ServerSideApply=true"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/tracking-method: annotation
spec:
  project: default
  source:
    repoURL: https://github.com/ray-project/kuberay
    targetRevision: v1.3.2
    path: helm-chart/kuberay-operator/crds
  destination:
    namespace: gpu-resources
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - Replace=true
