---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "kuberay-crds.fullname" . }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '6'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: kuberay-crds
    managed-by: argocd
    component: ml-infrastructure
    {{- include "kuberay-crds.labels" . | nindent 4 }}
spec:
  project: platform
  sources:
    - repoURL: https://ray-project.github.io/kuberay-helm/
      chart: kuberay-crds
      targetRevision: 1.3.0
      helm:
        releaseName: kuberay-crds
        valueFiles:
          - $values/platform/charts/kuberay-crds/values.yaml
    - repoURL: {{ .Values.global.repoURL | default "https://github.com/your-org/pn-infra.git" }}
      targetRevision: {{ .Values.global.targetRevision | default "v1.2.0-p0-infra" }}
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kuberay-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - PrunePropagationPolicy=foreground
      - Replace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
        - .metadata.annotations["cert-manager.io/inject-ca-from"]