---
# Global configuration
global:
  repoURL: 'https://github.com/pnow-devsupreme/pn-infra.git'
  targetRevision: 'main'
  targetNamespace: 'argocd'
  # Default hooks configuration (can be overridden by parent)
  hooks:
    enabled: true
    validation:
      infrastructure: false
      storage: true
    healthChecks:
      rookCeph: false
      monitoring: false
    notifications:
      syncFailure: true
    # Hook job configuration
    job:
      image: bitnami/kubectl:latest
      serviceAccountName: argocd-server
      ttlSecondsAfterFinished: 300
      backoffLimit: 3
    # Storage validation configuration
    storageValidation:
      requiredNamespaces:
        - rook-ceph
        - local-path-storage

# Labels configuration
labels:
  component: storage
  managed-by: argocd  # Override default Helm with ArgoCD

# Comprehensive Rook-Ceph configuration
# Based on official v1.18.3 with enhanced CSI, monitoring, and security

# Image configuration
image:
  repository: rook/ceph
  tag: v1.18.4
  pullPolicy: IfNotPresent

# Resource configuration for the operator
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Node selection and tolerations
nodeSelector:
  kubernetes.io/os: linux

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    effect: NoSchedule

crds:
  enabled: true


# CSI configuration - CSI operator is now default in v1.18+
csi:
  disableCsiDriver: false  # Enable CSI driver (default behavior)
  enableRbdDriver: true
  enableCephfsDriver: true
  enableGrpcMetrics: true
  enableCephfsSnapshotter: true
  enableRBDSnapshotter: true
  enableCSIEncryption: false

  provisionerReplicas: 2

  # Enable Ceph CSI Liveness sidecar deployment
  enableLiveness: true

  # CSI metrics configuration
  cephfsLivenessMetricsPort: 9081
  rbdLivenessMetricsPort: 8080

  serviceMonitor:
    enabled: true
    interval: 10s

  nfs:
    enabled: false

  topology:
    enabled: false

  # CSI Log level (0-5, higher = more verbose)
  logLevel: 0

  # GRPC timeout for CSI operations
  grpcTimeoutInSeconds: 150

# Discovery daemon configuration
enableDiscoveryDaemon: true

# Use Host Network for Operator
useOperatorHostNetwork: true



# Monitoring configuration
monitoring:
  enabled: true

# Security context
containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 2016
  runAsGroup: 2016
  capabilities:
    drop: ["ALL"]

# Operator settings
currentNamespaceOnly: false

# Log level
logLevel: INFO
