apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: root-application-project # change this to root-application-project only after all argo projects have been deployed.
  source:
    repoURL: git@github.com:pnow-devsupreme/pn-infra.git
    # targetRevision: v0.1.0-p0-foundation for first phase use this branch.
    targetRevision: v0.2.0-p0-infra
    path: applications/argocd-self
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: "30s"
        factor: 2
        maxDuration: "5m"
