{{- if .Values.configMap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    {{- range $key, $value := .Values.commonAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    {{- range $key, $value := .Values.commonLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- range $key, $value := .Values.commonSelectors }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- range $key, $value := .Values.configMap.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
data:
  {{- if .Values.configMap.statusbadge.enabled }}
  statusbadge.enabled: {{ .Values.configMap.statusbadge.enabled | quote }}
  {{- end }}
  {{- if .Values.configMap.exec.enabled }}
  exec.enabled: {{ .Values.configMap.exec.enabled | quote }}
  {{- end }}
  {{- if .Values.configMap.application.instanceLabelKey }}
  application.instanceLabelKey: {{ .Values.configMap.application.instanceLabelKey }}
  {{- end }}
  {{- if .Values.configMap.server.insecure }}
  server.insecure: {{ .Values.configMap.server.insecure | quote }}
  {{- end }}
  {{- if .Values.configMap.server.grpcWeb }}
  server.grpc.web: {{ .Values.configMap.server.grpcWeb | quote }}
  {{- end }}
  {{- if .Values.configMap.timeout.reconciliation }}
  timeout.reconciliation: {{ .Values.configMap.timeout.reconciliation }}
  {{- end }}
  {{- if .Values.configMap.timeout.hardReconciliation }}
  timeout.hard.reconciliation: {{ .Values.configMap.timeout.hardReconciliation }}
  {{- end }}
  {{- if .Values.configMap.repositories }}
  repositories: |
    {{- toYaml .Values.configMap.repositories | nindent 4 }}
  {{- end }}
  {{- if .Values.configMap.resourceCustomizations }}
  resource.customizations: |
    {{- toYaml .Values.configMap.resourceCustomizations | nindent 4 }}
  {{- end }}
{{- end }}
