apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  # Multiple sources: hooks + main application
  sources:
    # PreSync validation hook
    - repoURL: "https://github.com/ProficientNowTech/pn-infra.git"
      targetRevision: "main"
      path: v0.2.0/utils/hooks
      directory:
        include: "storage-presync-hook.yaml"
    # Main Rook-Ceph operator chart
    - repoURL: https://charts.rook.io/release
      chart: rook-ceph
      targetRevision: v1.18.3
      helm:
        values: |
          # Rook Ceph Operator Configuration - Based on official v1.18.3
          
          # Image configuration
          image:
            repository: rook/ceph
            tag: v1.18.3
            pullPolicy: IfNotPresent

          # Resource configuration for the operator
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

          # Node selection and tolerations
          nodeSelector:
            kubernetes.io/os: linux

          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Equal
              effect: NoSchedule

          # CSI configuration - CSI operator is now default in v1.18+
          csi:
            enableRbdDriver: true
            enableCephfsDriver: true
            enableGrpcMetrics: true
            # CSI images
            csiRBDProvisionerImage: registry.k8s.io/sig-storage/csi-provisioner:v5.1.0
            csiRBDAttacherImage: registry.k8s.io/sig-storage/csi-attacher:v4.7.0
            csiCephFSProvisionerImage: registry.k8s.io/sig-storage/csi-provisioner:v5.1.0
            csiCephFSAttacherImage: registry.k8s.io/sig-storage/csi-attacher:v4.7.0

          # Discovery daemon configuration
          enableDiscoveryDaemon: true
          
          # Monitoring configuration
          monitoring:
            enabled: true

          # Security context
          securityContext:
            runAsNonRoot: true
            runAsUser: 2016
            runAsGroup: 2016
            fsGroup: 2016

          # Feature toggles
          enableSelinuxRelabeling: false
          
          # Operator settings
          currentNamespaceOnly: false
          
          # Log level
          logLevel: INFO

  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - Replace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health check configuration
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
        - /status