# Production ArgoCD Projects Configuration
# Defines all projects needed for platform deployment

projects:
  - name: platform-core
    description: 'Core platform infrastructure and security'
    sourceRepos:
      - 'git@github.com:pnow-devsupreme/pn-infra.git'
      - 'https://charts.rook.io/release'
      - 'https://charts.bitnami.com/bitnami'
      - 'https://metallb.github.io/metallb'
      - 'https://kubernetes.github.io/ingress-nginx'
      - 'https://charts.jetstack.io'
      - 'https://helm.releases.hashicorp.com'
      - 'https://prometheus-community.github.io/helm-charts'
      - 'https://grafana.github.io/helm-charts'
      - 'https://kuberay-helm.github.io/helm-charts'
      - 'https://nvidia.github.io/gpu-operator'
    destinations:
      - namespace: metallb-system
        server: https://kubernetes.default.svc
      - namespace: ingress-nginx
        server: https://kubernetes.default.svc
      - namespace: cert-manager
        server: https://kubernetes.default.svc
      - namespace: argocd
        server: https://kubernetes.default.svc
      - namespace: rook-ceph
        server: https://kubernetes.default.svc
      - namespace: vault
        server: https://kubernetes.default.svc
      - namespace: monitoring
        server: https://kubernetes.default.svc
      - namespace: kuberay-system
        server: https://kubernetes.default.svc
      - namespace: gpu-operator-resources
        server: https://kubernetes.default.svc
    clusterResources:
      - group: '*'
        kind: '*'
      # - group: 'apiextensions.k8s.io'
      #   kind: 'CustomResourceDefinition'
      # - group: 'rbac.authorization.k8s.io'
      #   kind: 'ClusterRole'
      # - group: 'rbac.authorization.k8s.io'
      #   kind: 'ClusterRoleBinding'
      # - group: 'admissionregistration.k8s.io'
      #   kind: 'ValidatingAdmissionWebhook'
      # - group: 'admissionregistration.k8s.io'
      #   kind: 'MutatingAdmissionWebhook'
    namespaceResources:
      - group: '*'
        kind: '*'

  - name: platform-monitoring
    description: 'Monitoring and observability platform'
    sourceRepos:
      - 'git@github.com:pnow-devsupreme/pn-infra.git'
      - 'https://prometheus-community.github.io/helm-charts'
      - 'https://grafana.github.io/helm-charts'
    destinations:
      - namespace: monitoring
        server: https://kubernetes.default.svc
    clusterResources:
      - group: '*'
        kind: '*'
      # - group: 'rbac.authorization.k8s.io'
      #   kind: 'ClusterRole'
      # - group: 'rbac.authorization.k8s.io'
      #   kind: 'ClusterRoleBinding'
    namespaceResources:
      - group: '*'
        kind: '*'

  - name: platform-ml
    description: 'Machine learning and AI infrastructure'
    sourceRepos:
      - 'git@github.com:pnow-devsupreme/pn-infra.git'
      - 'https://kuberay-helm.github.io/helm-charts'
      - 'https://nvidia.github.io/gpu-operator'
    destinations:
      - namespace: kuberay-system
        server: https://kubernetes.default.svc
      - namespace: gpu-operator-resources
        server: https://kubernetes.default.svc
    clusterResources:
      - group: ''
        kind: '*'
      # - group: 'apiextensions.k8s.io'
      #   kind: 'CustomResourceDefinition'
      # - group: 'rbac.authorization.k8s.io'
      #   kind: 'ClusterRole'
      # - group: 'rbac.authorization.k8s.io'
      #   kind: 'ClusterRoleBinding'
    namespaceResources:
      - group: '*'
        kind: '*'
